# Generated by Django 5.1.6 on 2025-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["short_code"], name="short_code_index"),
        ),
        migrations.AlterModelTable(
            name="url",
            table="url",
        ),
    ]
